version: '3.7'

services:
  product-service:
    build: ./products
    volumes: 
      - ./products:/usr/src/app
    ports:
      - 5001:80

  login-api:
    build: ./login-api
    volumes:
      - ./login-api:/usr/src/login-api
    ports:
      - 8080:5000