version: '3.7'

services:
  product-service:
    build: ./products
    volumes: 
      - ./products:/usr/src/app
    ports:
      - 5001:80
    # deploy:
    #   restart-policy:
    #     condition: on-failure
    #     delay: 5s
    #     max_attempts: 3
    #     window: 120s

